/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import conexion.Conexion;
import util.PasswordUtil;


/**
 *
 * @author Usuario
 */
public class FrmAdministrarUsuarios extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdministrarUsuarios.class.getName());
private int Id = 0;
    /**
     * Creates new form FrmAdministrarUsuarios
     */
    public FrmAdministrarUsuarios() {
        initComponents();
        
            listarUsuarios();
            getContentPane().setBackground(
        new java.awt.Color(240,248,255));

this.setLocationRelativeTo(null);

setTitle("Administrar Usuarios");

jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16));

txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12));
txtApellido.setFont(new java.awt.Font("Segoe UI", 1, 12));
txtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12));
txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 12));
txtTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12));

cmbRol.setFont(
        new java.awt.Font("Segoe UI", 1, 12));

btnActualizarUsuario.setBackground(
        new java.awt.Color(52,152,219));

btnActualizarUsuario.setForeground(
        java.awt.Color.WHITE);

btnActualizarUsuario.setFont(
        new java.awt.Font(
                "Segoe UI",
                java.awt.Font.BOLD,
                12));

btnActualizarUsuario.setFocusPainted(false);
btnActualizarUsuario.setBorderPainted(false);
btnActualizarUsuario.setOpaque(true);

btnEliminar.setBackground(
        new java.awt.Color(231,76,60));

btnEliminar.setForeground(
        java.awt.Color.WHITE);

btnEliminar.setFont(
        new java.awt.Font(
                "Segoe UI",
                java.awt.Font.BOLD,
                12));

btnEliminar.setFocusPainted(false);
btnEliminar.setBorderPainted(false);
btnEliminar.setOpaque(true);

tblUsuarios.setRowHeight(25);

tblUsuarios.setFont(
        new java.awt.Font(
                "Segoe UI",
                0,
                13));

tblUsuarios.setGridColor(
        new java.awt.Color(220,220,220));

tblUsuarios.setSelectionBackground(
        new java.awt.Color(0,102,204));

tblUsuarios.setSelectionForeground(
        java.awt.Color.WHITE);

tblUsuarios.getTableHeader().setFont(
        new java.awt.Font(
                "Segoe UI",
                1,
                14));

tblUsuarios.getTableHeader().setBackground(
        new java.awt.Color(0,102,204));

tblUsuarios.getTableHeader().setForeground(
        java.awt.Color.WHITE);
   
    }
    public void listarUsuarios() {

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();

    modelo.setRowCount(0);

    try {

        java.sql.Connection con =
                new Conexion().establecerConexion();

        String sql = "SELECT * FROM Usuarios";

        java.sql.Statement st =
                con.createStatement();

        java.sql.ResultSet rs =
                st.executeQuery(sql);

        while (rs.next()) {

            modelo.addRow(new Object[]{

                rs.getInt("Id"),
                rs.getString("Nombre"),
                rs.getString("Apellido"),
                rs.getString("Usuario"),
                "********",
                rs.getString("Telefono"),
                rs.getString("Rol")

            });

        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                null,
                e.toString()
        );
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnActualizarUsuario = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cmbRol = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Usuario", "Contraseña", "Telefono", "Rol"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Rol");

        btnActualizarUsuario.setText("Actualizar");
        btnActualizarUsuario.addActionListener(this::btnActualizarUsuarioActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor", "Cliente" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtNombre))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(cmbRol, 0, 1, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnActualizarUsuario)
                        .addGap(40, 40, 40)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
int fila = tblUsuarios.getSelectedRow();

    Id = Integer.parseInt(
            tblUsuarios.getValueAt(fila, 0).toString()
    );

    txtNombre.setText(
            tblUsuarios.getValueAt(fila, 1).toString()
    );

    txtApellido.setText(
            tblUsuarios.getValueAt(fila, 2).toString()
    );

    txtUsuario.setText(
            tblUsuarios.getValueAt(fila, 3).toString()
    );

    txtPassword.setText("");

    txtTelefono.setText(
            tblUsuarios.getValueAt(fila, 5).toString()
    );

    cmbRol.setSelectedItem(
            tblUsuarios.getValueAt(fila, 6).toString()
    );       // TODO add your handling code here:
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
if (Id == 0) {

        javax.swing.JOptionPane.showMessageDialog(
                null,
                "Debe seleccionar un usuario para actualizar");

        return;
    }try {

    java.sql.Connection con =
            new Conexion().establecerConexion();

    String sql =
            "UPDATE Usuarios SET "
            + "Nombre=?, "
            + "Apellido=?, "
            + "Usuario=?, "
            + "Contrasena=?, "
            + "Telefono=?, "
            + "Rol=? "
            + "WHERE Id=?";

    java.sql.PreparedStatement ps =
            con.prepareStatement(sql);

   ps.setString(1, txtNombre.getText());
ps.setString(2, txtApellido.getText());
ps.setString(3, txtUsuario.getText());
String nuevaPassword = txtPassword.getText().trim();
if (!nuevaPassword.isEmpty()) {
    ps.setString(4, PasswordUtil.hash(nuevaPassword));
} else {
    try (java.sql.PreparedStatement psOld = con.prepareStatement(
            "SELECT Contrasena FROM Usuarios WHERE Id = ?")) {
        psOld.setInt(1, Id);
        try (java.sql.ResultSet rsOld = psOld.executeQuery()) {
            if (rsOld.next()) {
                ps.setString(4, rsOld.getString("Contrasena"));
            } else {
                ps.setString(4, "");
            }
        }
    }
}
ps.setString(5, txtTelefono.getText());
ps.setString(6, cmbRol.getSelectedItem().toString());
ps.setInt(7, Id);
    ps.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(
            null,
            "Usuario actualizado correctamente"
    );

    listarUsuarios();

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            null,
            e.toString()
    );

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
if (Id == 0) {

        javax.swing.JOptionPane.showMessageDialog(
                null,
                "Debe seleccionar un usuario para eliminar");

        return;
    }
        try {

    java.sql.Connection con =
            new Conexion().establecerConexion();

    String sql =
            "DELETE FROM Usuarios WHERE Id=?";

    java.sql.PreparedStatement ps =
            con.prepareStatement(sql);

    ps.setInt(1, Id);

    ps.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(
            null,
            "Usuario eliminado correctamente"
    );

    listarUsuarios();

    txtNombre.setText("");
    txtApellido.setText("");
    txtUsuario.setText("");
    txtPassword.setText("");
    txtTelefono.setText("");
    cmbRol.setSelectedIndex(0);

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            null,
            e.toString()
    );
     }   // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdministrarUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
