/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class FrmClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmClientes.class.getName());

    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() {
        initComponents();
         mostrarClientes();

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 16));
        setIconImage(
new javax.swing.ImageIcon(
getClass().getResource("/clientes.png")
).getImage()
);
        setTitle("Sistema de Clientes");

getContentPane().setBackground(
        new java.awt.Color(240,248,255));

this.setLocationRelativeTo(null);

// ===== LABELS =====
jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16));

// ===== TEXTFIELDS =====
jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12));
jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12));
jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12));
jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 12));
jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12));

// ===== GUARDAR =====
jButton1.setBackground(new java.awt.Color(46,204,113));
jButton1.setForeground(java.awt.Color.WHITE);
jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12));
jButton1.setFocusPainted(false);
jButton1.setBorderPainted(false);
jButton1.setOpaque(true);

// ===== ACTUALIZAR =====
jButton2.setBackground(new java.awt.Color(52,152,219));
jButton2.setForeground(java.awt.Color.WHITE);
jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12));
jButton2.setFocusPainted(false);
jButton2.setBorderPainted(false);
jButton2.setOpaque(true);

// ===== ELIMINAR =====
jButton3.setBackground(new java.awt.Color(231,76,60));
jButton3.setForeground(java.awt.Color.WHITE);
jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12));
jButton3.setFocusPainted(false);
jButton3.setBorderPainted(false);
jButton3.setOpaque(true);

// ===== NUEVO =====
jButton4.setBackground(new java.awt.Color(108,117,125));
jButton4.setForeground(java.awt.Color.WHITE);
jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12));
jButton4.setFocusPainted(false);
jButton4.setBorderPainted(false);
jButton4.setOpaque(true);

// ===== TABLA =====
jTable1.setRowHeight(25);

jTable1.setFont(
        new java.awt.Font("Segoe UI", 0, 13));

jTable1.setGridColor(
        new java.awt.Color(220,220,220));

jTable1.setSelectionBackground(
        new java.awt.Color(0,102,204));

jTable1.setSelectionForeground(
        java.awt.Color.WHITE);

jTable1.getTableHeader().setFont(
        new java.awt.Font("Segoe UI", 1, 14));

jTable1.getTableHeader().setBackground(
        new java.awt.Color(0,102,204));

jTable1.getTableHeader().setForeground(
        java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Teléfono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Dirección");

        jButton1.setBackground(new java.awt.Color(40, 167, 69));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 123, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(220, 53, 69));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(255, 193, 7));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Nuevo");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Telefono", "Correo", "Dirección"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCedula.setText("Cedula");

        txtCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(49, 49, 49)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(268, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, txtCedula});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, lblCedula, txtCedula});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if (jTextField1.getText().trim().isEmpty()
            && txtCedula.getText().trim().isEmpty()
            && jTextField2.getText().trim().isEmpty()
            && jTextField3.getText().trim().isEmpty()
            && jTextField4.getText().trim().isEmpty()
            && jTextField5.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "Debe ingresar al menos un cliente para guardar");

        return;
    }

        try {

    conexion.Conexion objetoConexion = new conexion.Conexion();

    java.sql.Connection conexionDB = objetoConexion.establecerConexion();

String sql = "INSERT INTO clientes "
           + "(Codigo, Cedula, Nombre, Telefono, Correo, Direccion) "
           + "VALUES (?, ?, ?, ?, ?, ?)";
    java.sql.PreparedStatement pst = conexionDB.prepareStatement(sql);

pst.setInt(1, Integer.parseInt(jTextField1.getText()));
pst.setString(2, txtCedula.getText());
pst.setString(3, jTextField2.getText());
pst.setString(4, jTextField3.getText());
pst.setString(5, jTextField4.getText());
pst.setString(6, jTextField5.getText());

pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(null, "Cliente guardado");
 mostrarClientes();
 limpiar();
} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.toString());

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jTextField1.setText("");
txtCedula.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int fila = jTable1.getSelectedRow();

jTextField1.setText(jTable1.getValueAt(fila, 0).toString());
txtCedula.setText(jTable1.getValueAt(fila, 1).toString());
jTextField2.setText(jTable1.getValueAt(fila, 2).toString());
jTextField3.setText(jTable1.getValueAt(fila, 3).toString());
jTextField4.setText(jTable1.getValueAt(fila, 4).toString());
jTextField5.setText(jTable1.getValueAt(fila, 5).toString());      // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (jTextField1.getText().trim().isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            null,
            "Debe seleccionar un cliente para actualizar");

    return;
}
        try {

    conexion.Conexion objetoConexion = new conexion.Conexion();

    java.sql.Connection conexionDB = objetoConexion.establecerConexion();

   String sql = "UPDATE clientes SET Cedula=?, Nombre=?, Telefono=?, Correo=?, Direccion=? WHERE Codigo=?";

    java.sql.PreparedStatement pst = conexionDB.prepareStatement(sql);

    pst.setString(1, txtCedula.getText());
pst.setString(2, jTextField2.getText());
pst.setString(3, jTextField3.getText());
pst.setString(4, jTextField4.getText());
pst.setString(5, jTextField5.getText());
pst.setInt(6, Integer.parseInt(jTextField1.getText()));

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(null, "Cliente actualizado");

    mostrarClientes();
    limpiar();

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.toString());

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (jTextField1.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(
            null,
            "Seleccione un cliente para eliminar");

    return;
}
        try {

    conexion.Conexion objetoConexion = new conexion.Conexion();

    java.sql.Connection conexionDB = objetoConexion.establecerConexion();

    String sql = "DELETE FROM clientes WHERE Codigo=?";

    java.sql.PreparedStatement pst = conexionDB.prepareStatement(sql);

    pst.setInt(1, Integer.parseInt(jTextField1.getText()));

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(null, "Cliente eliminado");

    mostrarClientes();
    limpiar();

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.toString());

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public void limpiar() {

    

    jTextField1.setText("");
    txtCedula.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");

}


    public void mostrarClientes() {

    try {

        conexion.Conexion objetoConexion = new conexion.Conexion();

        java.sql.Connection conexionDB = objetoConexion.establecerConexion();

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();

        modelo.addColumn("Código");
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Correo");
        modelo.addColumn("Dirección");

        jTable1.setModel(modelo);

        String sql = "SELECT * FROM clientes";

        java.sql.Statement st = conexionDB.createStatement();

        java.sql.ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            

            String[] datos = new String[6];

datos[0] = rs.getString("Codigo");
datos[1] = rs.getString("Cedula");
datos[2] = rs.getString("Nombre");
datos[3] = rs.getString("Telefono");
datos[4] = rs.getString("Correo");
datos[5] = rs.getString("Direccion");

            modelo.addRow(datos);
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(null, "Error al mostrar clientes: " + e.toString());

    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
