/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmProveedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProveedores.class.getName());

    /**
     * Creates new form FrmProveedores
     */
    public FrmProveedores() {
        initComponents();
                // ===== ESTILO GENERAL =====
       // ===== ESTILO REFERENCIA COMPRAS =====

setTitle("Sistema de Proveedores");

setIconImage(
new javax.swing.ImageIcon(
getClass().getResource("/proveedor.png")
).getImage()
);

this.setLocationRelativeTo(null);

getContentPane().setBackground(
        new java.awt.Color(240,248,255));

// ===== LABELS =====

jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16));
jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16));

// ===== TEXTFIELDS =====

jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12));
jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12));
jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12));

// ===== GUARDAR =====

jButton1.setBackground(
        new java.awt.Color(46,204,113));

jButton1.setForeground(
        java.awt.Color.WHITE);

jButton1.setFont(
        new java.awt.Font(
                "Segoe UI",
                java.awt.Font.BOLD,
                12));

jButton1.setFocusPainted(false);
jButton1.setBorderPainted(false);
jButton1.setOpaque(true);

// ===== ACTUALIZAR =====

jButton2.setBackground(
        new java.awt.Color(52,152,219));

jButton2.setForeground(
        java.awt.Color.WHITE);

jButton2.setFont(
        new java.awt.Font(
                "Segoe UI",
                java.awt.Font.BOLD,
                12));

jButton2.setFocusPainted(false);
jButton2.setBorderPainted(false);
jButton2.setOpaque(true);

// ===== ELIMINAR =====

jButton3.setBackground(
        new java.awt.Color(231,76,60));

jButton3.setForeground(
        java.awt.Color.WHITE);

jButton3.setFont(
        new java.awt.Font(
                "Segoe UI",
                java.awt.Font.BOLD,
                12));

jButton3.setFocusPainted(false);
jButton3.setBorderPainted(false);
jButton3.setOpaque(true);

// ===== NUEVO =====

jButton4.setBackground(
        new java.awt.Color(108,117,125));

jButton4.setForeground(
        java.awt.Color.WHITE);

jButton4.setFont(
        new java.awt.Font(
                "Segoe UI",
                java.awt.Font.BOLD,
                12));

jButton4.setFocusPainted(false);
jButton4.setBorderPainted(false);
jButton4.setOpaque(true);

// ===== TABLA =====

jTable1.setRowHeight(25);

jTable1.setFont(
        new java.awt.Font(
                "Segoe UI",
                0,
                13));

jTable1.setGridColor(
        new java.awt.Color(220,220,220));

jTable1.setSelectionBackground(
        new java.awt.Color(0,102,204));

jTable1.setSelectionForeground(
        java.awt.Color.WHITE);

jTable1.getTableHeader().setFont(
        new java.awt.Font(
                "Segoe UI",
                1,
                14));

jTable1.getTableHeader().setBackground(
        new java.awt.Color(0,102,204));

jTable1.getTableHeader().setForeground(
        java.awt.Color.WHITE);

        mostrarProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Proveedor");
        jLabel2.setToolTipText("");

        jLabel3.setText("Teléfono");
        jLabel3.setToolTipText("");

        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Actualizar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Nuevo");
        jButton4.setToolTipText("");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Proveedor", "Teléfono"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if (jTextField1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null,
                "Ingresa el código del proveedor");
        return;
    }

    if (jTextField2.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null,
                "Ingresa el nombre del proveedor");
        return;
    }

    if (jTextField3.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null,
                "Ingresa el teléfono del proveedor");
        return;
    }
try {

    conexion.Conexion objetoConexion =
    new conexion.Conexion();

    java.sql.Connection conexionDB =
    objetoConexion.establecerConexion();

    String sql =
    "INSERT INTO proveedores (Codigo, Proveedor, Telefono) VALUES (?, ?, ?)";

    java.sql.PreparedStatement pst =
    conexionDB.prepareStatement(sql);

    pst.setInt(1,
    Integer.parseInt(jTextField1.getText()));

    pst.setString(2,
    jTextField2.getText());

    pst.setString(3,
    jTextField3.getText());

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(null,
    "Proveedor guardado");

    mostrarProveedores();

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(null,
    "Error: " + e.toString());

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    if (jTable1.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(null,
                "Debe seleccionar una fila para eliminar el proveedor");
        return;
    }
    if (jTextField1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null,
                "Ingresa el código del proveedor");
        return;
    }

    if (jTextField2.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null,
                "Ingresa el nombre del proveedor");
        return;
    }

    if (jTextField3.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null,
                "Ingresa el teléfono del proveedor");
        return;
    }
try {

    conexion.Conexion objetoConexion =
    new conexion.Conexion();

    java.sql.Connection conexionDB =
    objetoConexion.establecerConexion();

    String sql =
    "DELETE FROM proveedores WHERE Codigo=?";

    java.sql.PreparedStatement pst =
    conexionDB.prepareStatement(sql);

    pst.setInt(1,
    Integer.parseInt(jTextField1.getText()));

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(null,
    "Proveedor eliminado");

    mostrarProveedores();

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(null,
    "Error: " + e.toString());

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (jTable1.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(null,
                "Debe seleccionar una fila para actualizar el proveedor");
        return;
    }try {

    conexion.Conexion objetoConexion =
    new conexion.Conexion();

    java.sql.Connection conexionDB =
    objetoConexion.establecerConexion();

    String sql =
    "UPDATE proveedores SET Proveedor=?, Telefono=? WHERE Codigo=?";

    java.sql.PreparedStatement pst =
    conexionDB.prepareStatement(sql);

    pst.setString(1,
    jTextField2.getText());

    pst.setString(2,
    jTextField3.getText());

    pst.setInt(3,
    Integer.parseInt(jTextField1.getText()));

    pst.executeUpdate();

    javax.swing.JOptionPane.showMessageDialog(null,
    "Proveedor actualizado");

    mostrarProveedores();

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(null,
    "Error: " + e.toString());

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int fila = jTable1.getSelectedRow();

jTextField1.setText(
jTable1.getValueAt(fila, 0).toString());

jTextField2.setText(
jTable1.getValueAt(fila, 1).toString());

jTextField3.setText(
jTable1.getValueAt(fila, 2).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public void mostrarProveedores() {
        try {
            conexion.Conexion objetoConexion = new conexion.Conexion();
            java.sql.Connection conexionDB = objetoConexion.establecerConexion();

            javax.swing.table.DefaultTableModel modelo =
                    new javax.swing.table.DefaultTableModel();

            modelo.addColumn("Código");
            modelo.addColumn("Proveedor");
            modelo.addColumn("Teléfono");

            jTable1.setModel(modelo);

            String sql = "SELECT * FROM proveedores ORDER BY Codigo";
            java.sql.Statement st = conexionDB.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("Codigo"),
                    rs.getString("Proveedor"),
                    rs.getString("Telefono")
                });
            }

            rs.close();
            st.close();
            conexionDB.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Error al mostrar proveedores: " + e.getMessage());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProveedores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
